name: Java CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: build_and_test


    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'

      - name: Build artifact
        run: mvn clean package -DskipTests


      - name: Deploy to Staging
        uses: easingthemes/ssh-deploy@main
        env:
          SOURCE: target/*.jar
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}