name: Deploy to staging

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Staging
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
